DROP TABLE IF EXISTS BQ2_SOLUTION;

CREATE EXTERNAL TABLE BQ2_SOLUTION
(
COUNTRY_NAME STRING
, AVERAGE DOUBLE
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
LOCATION '/user/cloudera/Project2/hive/tables/BQ2_SOLUTION/';

INSERT OVERWRITE TABLE BQ2_SOLUTION SELECT
COUNTRY_NAME
, (`2015`-`2000`) / 15 AS AVERAGE
FROM BQ2;
