-- create table with for sqoop import output--
DROP TABLE IF EXISTS GENDER_STATS_DB.BQ1;
CREATE EXTERNAL TABLE GENDER_STATS_DB.BQ1
(COUNTRY_NAME STRING, YEAR_COL INT, DATA_COL DECIMAL(38,30))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
TBLPROPERTIES("skip.header.line.count"="1");

--Load data from sqoop import output --
LOAD LOCAL DATA INPATH '/home/cloudera/BQ1/part-m-00000' INTO TABLE GENDER_STATS_DB.BQ1;

-- show only records with countries that the average is less than 30
DROP TABLE IF EXISTS GENDER_STATS_DB.BQ1_AVERAGES_LESS_30;
CREATE TABLE GENDER_STATS_DB.BQ1_AVERAGES_LESS_30 AS SELECT * FROM GENDER_STATS_DB.BQ1
WHERE AVERAGE < 30;

-- show only countries where in any year the percentage was less than 30
DROP TABLE IF EXISTS GENDER_STATS_DB.BQ1_LESS_30;
CREATE TABLE GENDER_STATS_DB.BQ1_LESS_30 AS 
SELECT COUNTRY_NAME,MIN(data_col) AS DATA_COUNT FROM GENDER_STATS_DB.BQ1
WHERE DATA_COL < 30
GROUP BY COUNTRY_NAME
ORDER BY COUNTRY_NAME ASC;

--SELECT * FROM gender_stats_db.bq1_less_30 ORDER BY country_name ASC;
--SELECT * FROM gender_stats_db.bq1_averages_less_30;