-- Create view BQ1
CREATE OR REPLACE VIEW BQ1
AS
SELECT *
FROM GENDER_STATS_DATA
WHERE UPPER(INDICATOR_CODE)='SE.TER.CMPL.FE.ZS';

-- Create view BQ2
CREATE OR REPLACE VIEW BQ2
AS
SELECT *
FROM GENDER_STATS_DATA
WHERE UPPER(COUNTRY_NAME)='UNITED STATES'
AND UPPER(INDICATOR_CODE)='SE.TER.ENRR.FE';

-- Create view BQ3
CREATE OR REPLACE VIEW BQ3
AS SELECT *
FROM GENDER_STATS_DATA
WHERE UPPER(COUNTRY_NAME)='UNITED STATES'
AND UPPER(INDICATOR_CODE)='SL.EMP.TOTL.SP.MA.ZS';

-- Create view BQ4
CREATE OR REPLACE VIEW BQ4
AS
SELECT *
FROM GENDER_STATS_DATA
WHERE UPPER(COUNTRY_NAME)='UNITED STATES'
AND UPPER(INDICATOR_CODE)='SL.EMP.TOTL.SP.FE.ZS';

-- Create view BQ5
CREATE OR REPLACE VIEW BQ5
AS
SELECT *
FROM GENDER_STATS_DATA
WHERE UPPER(INDICATOR_CODE)='SL.EMP.TOTL.SP.FE.ZS'
OR UPPER(INDICATOR_CODE)='SL.EMP.TOTL.SP.MA.ZS';
